### ISSUE TITLE
Make Maximum Message Size Configurable

### ISSUE THREAD

**Issue by micahcc** [mattgodbolt/seasocks#150] opened 2021-01-06 00:30 UTC
Right now websocket messages are capped 16k, it would be nice if this was configurable.

https://github.com/mattgodbolt/seasocks/blob/master/src/main/c/Connection.cpp#L154

**Comment by mattgodbolt** [comment] 2021-01-06 02:27
Duplicate of #93

**Closed by mattgodbolt** 2021-01-06 02:27 UTC
